spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&characterEncoding=utf8
    username: mybatis
    password: MyBatis@55998
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.hut.myblog.bean

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#头像
comment.avatar: /images/avatar.png


